# Generated by Django 2.1.7 on 2019-03-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标题')),
                ('picture', models.CharField(default='', max_length=255, verbose_name='图标链接')),
                ('spend', models.IntegerField(verbose_name='资费')),
                ('desc', models.CharField(max_length=255, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('count', models.IntegerField(verbose_name='访问次数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment_users', models.ManyToManyField(blank=True, null=True, to='comment.Discuss', verbose_name='所有用的评论')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Lecturer')),
                ('like_users', models.ManyToManyField(blank=True, null=True, to='user.User', verbose_name='所有点赞的用户')),
            ],
            options={
                'verbose_name': '单个课程',
                'verbose_name_plural': '单个课程',
                'db_table': 'code_course_signal',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_picture', models.CharField(default='', max_length=255, verbose_name='图标链接')),
                ('course_name', models.CharField(max_length=255, verbose_name='课程名')),
                ('course_count', models.IntegerField(verbose_name='课时数')),
                ('course_total_spend', models.IntegerField(verbose_name='总资费')),
                ('course_type', models.CharField(choices=[('online', '线上'), ('offline', '线下')], max_length=255, verbose_name='课程类别(线下OR线上)')),
                ('course_desc', models.CharField(max_length=255, verbose_name='大纲描述')),
                ('course_user_join', models.ManyToManyField(blank=True, null=True, to='user.User', verbose_name='所有加入的用户')),
                ('courses', models.ManyToManyField(to='course.Course', verbose_name='大纲对应的所有课时')),
            ],
            options={
                'verbose_name': '课程大纲',
                'verbose_name_plural': '课程大纲',
                'db_table': 'code_course_system',
                'ordering': ['-id'],
            },
        ),
    ]
