# Generated by Django 2.1.7 on 2019-03-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_specialoffer'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsystem',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.SpecialOffer'),
        ),
    ]
