# Generated by Django 2.1.7 on 2019-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='技能名称')),
                ('skill_pic', models.URLField(default='', max_length=255, verbose_name='技能图标')),
                ('skill_desc', models.CharField(default='', max_length=255, verbose_name='技能描述')),
            ],
            options={
                'verbose_name': '技能树',
                'verbose_name_plural': '技能树',
                'db_table': 'code_other_skills',
                'ordering': ['-id'],
            },
        ),
    ]
