# Generated by Django 2.1.7 on 2019-03-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('other', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_name', models.CharField(max_length=255, verbose_name='讲师姓名')),
                ('lec_idcard', models.CharField(max_length=255, verbose_name='讲师身份证号')),
                ('lec_avatar', models.URLField(default='', verbose_name='讲师头像链接')),
                ('lec_address', models.CharField(default='', max_length=255, verbose_name='讲师住址')),
                ('lec_level', models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('university', '大学'), ('graduate', '研究生'), ('master', '博士'), ('social', '社会')], max_length=255, verbose_name='讲师学历')),
                ('lec_age', models.IntegerField(verbose_name='讲师年龄')),
                ('lec_desc', models.CharField(max_length=255, verbose_name='讲师描述')),
                ('lec_join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('lec_skill', models.ManyToManyField(to='other.Skill', verbose_name='讲师技能')),
            ],
            options={
                'verbose_name': '讲师管理',
                'verbose_name_plural': '讲师管理',
                'db_table': 'code_user_lecturer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='充值金额')),
                ('code', models.CharField(max_length=255, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'code_user_recharge',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SpendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='花费金额')),
                ('code', models.CharField(max_length=255, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
                'db_table': 'code_user_spend',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='匿名', max_length=255, verbose_name='用户名')),
                ('user_phone', models.CharField(default='', max_length=255, verbose_name='手机号')),
                ('user_avatar', models.URLField(default='', verbose_name='用户头像链接')),
                ('user_address', models.CharField(default='', max_length=255, verbose_name='用户详情住址')),
                ('user_level', models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('university', '大学'), ('master', '更高学历'), ('social', '社会')], max_length=255, verbose_name='用户年级')),
                ('user_age', models.IntegerField(verbose_name='用户年龄')),
                ('user_eng_level', models.CharField(choices=[('cet4', '英语四级'), ('cet6', '英语六级'), ('master', '精通英语'), ('normal', '普通读写'), ('poor', '入门基础')], max_length=255, verbose_name='用户英语能力')),
                ('user_money', models.IntegerField(default=0, verbose_name='账户余额')),
                ('user_join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('discount_coupon', models.ManyToManyField(blank=True, null=True, to='activity.Discount', verbose_name='拥有的优惠券')),
                ('expect_skill', models.ManyToManyField(to='other.Skill', verbose_name='期望技能')),
            ],
            options={
                'verbose_name': '注册用户',
                'verbose_name_plural': '注册用户',
                'db_table': 'code_user_user',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='spendrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='购买用户'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='充值用户'),
        ),
    ]
